version: '3.8'

services:
  cobale-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://cobale_user:cobale_pass@db:5432/cobale_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cobale_user
      POSTGRES_PASSWORD: cobale_pass
      POSTGRES_DB: cobale_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
